table 'Measures to calculate Performing Vehicles'
	lineageTag: 2766b8f0-d850-4b83-85a9-e30365f3653d

	measure 'Cost Per Mile' = DIVIDE(SUM(FLMaintenance_info[MaintenanceCost]),SUM(Fleet_SharePoint_Trips_2020_2022[DistanceKM]),0)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: bcc47bd2-edb3-44f3-bb6f-c10c9751552d

	measure Downtime/km = DIVIDE(SUM(FLMaintenance_info[DowntimeHours]),SUM(Fleet_SharePoint_Trips_2020_2022[DistanceKM]),0)
		lineageTag: f16a3d03-4243-4867-8d63-24f5afbe4e63

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Vehicle Performance Score' = ```
			
			var costweight = 0.4
			var downtimeweight=0.3
			var kmweight =0.3
			-- calculating vehicle downtime score
			var Downtime_Score = 
			    var max_socre = MAXX(ALL(Vehicle_Info[Vehicle_Name]),[Downtime/km])
			    var min_score = MINX(ALL(Vehicle_Info[Vehicle_Name]),[Downtime/km])
			    return 
			        1-DIVIDE([Downtime/km]-min_score,max_socre-min_score,0)
			-- calculating vehicle maintenance cost score 
			var Cost_Score = 
			    var maxcost = maxx(ALL(Vehicle_Info[Vehicle_Name]),[Cost Per Mile])
			    var mincost = MINX(ALL(Vehicle_Info[Vehicle_Name]),[Cost Per Mile])
			
			    return 
			        1-DIVIDE(([Cost Per Mile]-mincost),(maxcost-mincost),0)
			-- calculating vehicle km driven score
			var KM_Score = 
			    var maxscore = MAXX(ALL(Vehicle_Info[Vehicle_Name]),CALCULATE(SUM(Fleet_SharePoint_Trips_2020_2022[DistanceKM])))
			    var minscore =  MINX(ALL(Vehicle_Info[Vehicle_Name]),CALCULATE(SUM(Fleet_SharePoint_Trips_2020_2022[DistanceKM])))
			    return 
			        DIVIDE(SUM(Fleet_SharePoint_Trips_2020_2022[DistanceKM])-minscore,maxscore-minscore,0)
			
			return 
			    (costweight*Cost_Score)+(downtimeweight*Downtime_Score)+(kmweight*KM_Score)
			
			
			
			
			
			
			
			
			
			
			
			
			```
		formatString: 0.00
		lineageTag: 260c1d44-5be0-4eba-91d0-aaffca0e6d39

	measure datacheck = ```
			
			var hasdwthrs = NOT(ISBLANK(SUM(FLMaintenance_info[DowntimeHours])))
			var hasmatcost = NOT(ISBLANK(SUM(FLMaintenance_info[MaintenanceCost])))
			var kmdrven =NOT(ISBLANK(SUM(Fleet_SharePoint_Trips_2020_2022[DistanceKM])))
			
			return 
			    if (hasdwthrs&&hasmatcost&&kmdrven ,"completed","notcompletd")
			    
			```
		lineageTag: 57dfe6a2-dbc9-4675-84c9-f65ba27ddb5c

	measure Cost_Score = ```
			
			    var maxcost = maxx(ALL(Vehicle_Info[Vehicle_Name]),[Cost Per Mile])
			    var mincost = MINX(ALL(Vehicle_Info[Vehicle_Name]),[Cost Per Mile])
			
			    return 
			        1-DIVIDE(([Cost Per Mile]-mincost),(maxcost-mincost),0)
			```
		lineageTag: b91d9469-0d53-4c64-bf57-3d9f816b7af9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Downtime_Score = ```
			
			    var maxsocre = MAXX(ALL(Vehicle_Info[Vehicle_Name]),[Downtime/km])
			    var minscore = MINX(ALL(Vehicle_Info[Vehicle_Name]),[Downtime/km])
			    return 
			        1-DIVIDE([Downtime/km]-minscore,maxsocre-minscore,0)
			```
		lineageTag: 2393f7fb-71cc-40f7-8ce8-e5237a29d988

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure KM_Score = ```
			
			    var maxscore = MAXX(ALL(Vehicle_Info[Vehicle_Name]),CALCULATE(SUM(Fleet_SharePoint_Trips_2020_2022[DistanceKM])))
			    var minscore =  MINX(ALL(Vehicle_Info[Vehicle_Name]),CALCULATE(SUM(Fleet_SharePoint_Trips_2020_2022[DistanceKM])))
			    return 
			        DIVIDE(SUM(Fleet_SharePoint_Trips_2020_2022[DistanceKM])-minscore,maxscore-minscore,0)
			```
		lineageTag: cd29ce3f-9d16-417b-a0a5-4db35630d020

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Vehicle Rank By Performance' = RANKX(ALL(Vehicle_Info[Vehicle_Name]), [Vehicle Performance Score],,ASC,Dense)
		formatString: 0
		lineageTag: 3e1c6587-e3d7-4b07-a811-acef173ce531

	measure '1st Vehicle Worst Vehicle' = ```
			
			VAR WorstVehicleTable =
			    TOPN(
			        1,
			        ALL(Vehicle_Info[Vehicle_Name]),
			        [Vehicle Performance Score],
			        ASC
			    )
			RETURN
			    CONCATENATEX(
			        WorstVehicleTable,
			        Vehicle_Info[Vehicle_Name],", "
			        
			    )
			```
		lineageTag: 26c4d9cc-3ee8-4268-ad66-f630d83bad79

	measure '2nd Vehicle Worst Vehicle' =
			
			VAR WorstVehicleTable =
			    TOPN(
			        2,
			        ALL(Vehicle_Info[Vehicle_Name]),
			        [Vehicle Performance Score],
			        ASC
			    )
			RETURN
			    CONCATENATEX(
			        WorstVehicleTable,
			        Vehicle_Info[Vehicle_Name],
			        ", "
			    )
		lineageTag: 093d6129-cab3-4344-abb1-ac7a2321cddf

	measure '3 Worst Vehicle Vehicle' =
			
			VAR WorstVehicleTable =
			    TOPN(
			        3,
			        ALL(Vehicle_Info[Vehicle_Name]),
			        [Vehicle Performance Score],
			        ASC
			    )
			RETURN
			    CONCATENATEX(
			        WorstVehicleTable,
			        Vehicle_Info[Vehicle_Name],
			        ", "
			    )
		lineageTag: b031460e-80fe-4f00-9b8a-948af5f02933

	measure '3 Worst Vehicles downtitme' =
			
			VAR WorstVehicleTable =
			    TOPN(
			        3,
			        ALL(Vehicle_Info[Vehicle_Name]),
			        [Vehicle Performance Score],
			        ASC
			    )
			RETURN
			CALCULATE(
			    SUM(FLMaintenance_info[DowntimeHours]),
			    KEEPFILTERS(WorstVehicleTable)
			)
		formatString: 0
		lineageTag: 385d8b79-6d4a-41d0-829d-6546b374820b

	column Column
		formatString: 0
		lineageTag: e5bbc75b-36ab-4643-b5f6-8f0a07e5b236
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition 'Measures to calculate Performing Vehicles' = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 20320aa982434a4f9f4a6f3f9b889192

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

