table 'Measures to effeciecy'
	lineageTag: 7af2e301-700e-475d-b8ba-c617b0f1c475

	measure 'Arrow For Vehicle DwontimeHrs' = IF(ISBLANK([reduced vehicle downtime hrs]),BLANK(),if([reduced vehicle downtime hrs]>0,"🡅","🡇"))
		lineageTag: f27347eb-7e4d-430a-8f29-4fa121cfff44

	measure Arrow = IF(ISBLANK([workshop efficiency in hrs]),BLANK(),if([workshop efficiency in hrs]>0,"🡅","🡇"))
		lineageTag: 98946d1e-a38e-41b1-95e6-befb6c8abc5b

	measure 'reduced vehicle downtime hrs' = if(ISBLANK([sameperiodlast yr downtimehrs]),BLANK(),SUM(FLMaintenance_info[DowntimeHours])-[sameperiodlast yr downtimehrs])
		formatString: 0
		lineageTag: 0db007fc-6e92-4ebe-83df-8be27f7dad47

	measure 'Reduced Vehicle Downtime in %' = DIVIDE([reduced vehicle downtime hrs],[sameperiodlast yr downtimehrs])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: cf8bb6a6-89d5-418a-a0b8-5ce4d16bc758

	measure 'sameperiodlast yr downtimehrs' =
			
			IF(ISFILTERED(Date_Table[Date].[Day])||ISFILTERED(Date_Table[Date].[Month])||ISFILTERED(Date_Table[Date].[Quarter])||ISFILTERED(Date_Table[Date].[Year]),CALCULATE(SUM(FLMaintenance_info[DowntimeHours]),SAMEPERIODLASTYEAR(Date_Table[Date])),BLANK())
		formatString: 0
		lineageTag: 86e52178-c092-4b6f-84a6-afe5847c72a1

	measure 'sameperiodlastyear repair time hrs' = ```
			
			 if (ISFILTERED(Date_Table[Date].[Month])|| ISFILTERED(Date_Table[Date].[Quarter])||ISFILTERED(Date_Table[Date].[Year]) || ISFILTERED(Date_Table[Date].[Day]),CALCULATE(SUM('Fleet_Maintenance_Info(XL)'[RepairTimeHours]), SAMEPERIODLASTYEAR(Date_Table[Date])),BLANK())
			```
		formatString: 0
		lineageTag: 2a9019f9-14e5-4bab-a9df-f5e22dcb4843

	measure 'Workshop Efficiency in %' = DIVIDE([workshop efficiency in hrs],[sameperiodlastyear repair time hrs])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c9a40044-d0c1-434e-b532-17946a647423

	measure 'workshop efficiency in hrs' = ```
			
			 if ((ISFILTERED(Date_Table[Date].[Month])|| ISFILTERED(Date_Table[Date].[Quarter])||ISFILTERED(Date_Table[Date].[Year])||ISFILTERED(Date_Table[Date].[Day])),IF(ISBLANK([sameperiodlastyear repair time hrs]),BLANK(), [sameperiodlastyear repair time hrs]-SUM('Fleet_Maintenance_Info(XL)'[RepairTimeHours])),BLANK())
			```
		formatString: 0
		lineageTag: 1216efcf-0a3d-4298-8935-e0a8cf7a2a39

	measure 'Arrow For Mant Cst' = IF(ISBLANK([MaintenanceCostCOmparison in %]),BLANK(),if([MaintenanceCostCOmparison in %]>0,"🡅","🡇"))
		lineageTag: b3864959-c60a-4152-b896-dfa20d441ae4

	measure SamePeriodLastYrMntCst = ```
			IF(ISFILTERED(Date_Table[Date].[Day])||ISFILTERED(Date_Table[Date].[Month])||ISFILTERED(Date_Table[Date].[Quarter])||ISFILTERED(Date_Table[Date].[Year]),CALCULATE(SUM(FLMaintenance_info[MaintenanceCost]),SAMEPERIODLASTYEAR(Date_Table[Date])),BLANK())
			
			
			```
		formatString: 0
		lineageTag: e795181e-3c57-4c3b-afce-ed81508dacff

	measure 'Maitanancecost comparison' = SUM(FLMaintenance_info[MaintenanceCost]) -[SamePeriodLastYrMntCst]
		formatString: 0
		lineageTag: a4262b26-1ed5-4fd2-a94b-8ba78f9d6a4c

	measure 'MaintenanceCostCOmparison in %' = DIVIDE([Maitanancecost comparison],[SamePeriodLastYrMntCst])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f48a66ee-9d3e-4705-9485-b618767b9ae6

	measure SamePeriodLastYrRepairTimeHrs = IF(ISFILTERED(Date_Table[Date].[Day])||ISFILTERED(Date_Table[Date].[Month])||ISFILTERED(Date_Table[Date].[Quarter])||ISFILTERED(Date_Table[Date].[Year]),CALCULATE(SUM('Fleet_Maintenance_Info(XL)'[RepairTimeHours]),SAMEPERIODLASTYEAR(Date_Table[Date])))
		formatString: 0
		lineageTag: 4ad2f7b8-aa55-4fb0-a93a-ccf70805932c

	measure RepairTimeHrsComparison = SUM('Fleet_Maintenance_Info(XL)'[RepairTimeHours]) - [sameperiodlastyear repair time hrs]
		formatString: 0
		lineageTag: 8b2b2bb4-2aa6-4155-8dc8-b1496ad1f658

	measure 'RepairTimeHrsComparison in %' = DIVIDE([RepairTimeHrsComparison],[sameperiodlastyear repair time hrs])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 952946c0-d60e-4af3-92a6-3ff59d2e7ddd

	measure ArrowForRepairTimeHrs = IF(ISBLANK([RepairTimeHrsComparison in %]),BLANK(),if([RepairTimeHrsComparison in %]>0,"🡅","🡇"))
		lineageTag: 5dd13229-55cb-421d-9547-9c81a1c4c6fa

	measure '6 months ago downtime' = DIVIDE(CALCULATE(SUM(FLMaintenance_info[DowntimeHours]),DATEADD(Date_Table[Date],-6,MONTH)),6)
		formatString: 0
		lineageTag: bc9168e0-1203-407d-896d-2a557aece3c2

	column Column
		formatString: 0
		lineageTag: 6ce6f14f-0d26-4b7a-8942-8e4bfceefb3b
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition 'Measures to effeciecy' = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 38cfd2cdbf7a4b17824d604f1adcd131

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

