table 'Measures to effeciecy'
	lineageTag: 7af2e301-700e-475d-b8ba-c617b0f1c475

	measure 'Arrow For Vehicle DwontimeHrs' = IF(ISBLANK([reduced vehicle downtime hrs]),BLANK(),if([reduced vehicle downtime hrs]>0,"🡅","🡇"))
		lineageTag: f27347eb-7e4d-430a-8f29-4fa121cfff44

	measure Arrow = IF(ISBLANK([workshop efficiency in hrs]),BLANK(),if([workshop efficiency in hrs]>0,"🡅","🡇"))
		lineageTag: 98946d1e-a38e-41b1-95e6-befb6c8abc5b

	measure 'reduced vehicle downtime hrs' = if(ISBLANK([sameperiodlast yr downtimehrs]),BLANK(),[sameperiodlast yr downtimehrs]-SUM(FLMaintenance_info[DowntimeHours]))
		formatString: 0
		lineageTag: 0db007fc-6e92-4ebe-83df-8be27f7dad47

	measure 'Reduced Vehicle Downtime in %' = DIVIDE([reduced vehicle downtime hrs],[sameperiodlast yr downtimehrs])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: cf8bb6a6-89d5-418a-a0b8-5ce4d16bc758

	measure 'sameperiodlast yr downtimehrs' =
			
			IF(ISFILTERED(Date_Table[Date].[Day])||ISFILTERED(Date_Table[Date].[Month])||ISFILTERED(Date_Table[Date].[Quarter])||ISFILTERED(Date_Table[Date].[Year]),CALCULATE(SUM(FLMaintenance_info[DowntimeHours]),SAMEPERIODLASTYEAR(Date_Table[Date])),BLANK())
		formatString: 0
		lineageTag: 86e52178-c092-4b6f-84a6-afe5847c72a1

	measure 'sameperiodlastyear repair time hrs' = ```
			
			 if (ISFILTERED(Date_Table[Date].[Month])|| ISFILTERED(Date_Table[Date].[Quarter])||ISFILTERED(Date_Table[Date].[Year]) || ISFILTERED(Date_Table[Date].[Day]),CALCULATE(SUM('Fleet_Maintenance_Info(XL)'[RepairTimeHours]), SAMEPERIODLASTYEAR(Date_Table[Date])),BLANK())
			```
		formatString: 0
		lineageTag: 2a9019f9-14e5-4bab-a9df-f5e22dcb4843

	measure 'Workshop Efficiency in %' = DIVIDE([workshop efficiency in hrs],[sameperiodlastyear repair time hrs])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c9a40044-d0c1-434e-b532-17946a647423

	measure 'workshop efficiency in hrs' = ```
			
			 if ((ISFILTERED(Date_Table[Date].[Month])|| ISFILTERED(Date_Table[Date].[Quarter])||ISFILTERED(Date_Table[Date].[Year])||ISFILTERED(Date_Table[Date].[Day])),IF(ISBLANK([sameperiodlastyear repair time hrs]),BLANK(), [sameperiodlastyear repair time hrs]-SUM('Fleet_Maintenance_Info(XL)'[RepairTimeHours])),BLANK())
			```
		formatString: 0
		lineageTag: 1216efcf-0a3d-4298-8935-e0a8cf7a2a39

	column Column
		formatString: 0
		lineageTag: 6ce6f14f-0d26-4b7a-8942-8e4bfceefb3b
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition 'Measures to effeciecy' = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 38cfd2cdbf7a4b17824d604f1adcd131

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

